<a href="https://colab.research.google.com/github/harshchaturkar/Mini-Project-repo/blob/main/assignment_23.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("./heart.csv")
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [ ]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [ ]:
df.tail()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [ ]:
df.dtypes

Age                 int64
Sex                object
ChestPainType      object
RestingBP           int64
Cholesterol         int64
FastingBS           int64
RestingECG         object
MaxHR               int64
ExerciseAngina     object
Oldpeak           float64
ST_Slope           object
HeartDisease        int64
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

In [ ]:
df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [ ]:
df.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [ ]:
duplicated = df.duplicated().sum()
duplicated

np.int64(0)

In [ ]:
df.drop_duplicates()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [ ]:
X = df.drop("HeartDisease", axis = 1)
y = df["HeartDisease"]
print("Independent features :")
print(X.head())
print("\nDependent feature :")
print(y.head())

Independent features :
   Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172
1   49   F           NAP        160          180          0     Normal    156
2   37   M           ATA        130          283          0         ST     98
3   48   F           ASY        138          214          0     Normal    108
4   54   M           NAP        150          195          0     Normal    122

  ExerciseAngina  Oldpeak ST_Slope
0              N      0.0       Up
1              N      1.0     Flat
2              N      0.0       Up
3              Y      1.5     Flat
4              N      0.0       Up

Dependent feature :
0    0
1    1
2    0
3    1
4    0
Name: HeartDisease, dtype: int64

In [ ]:
#cat_cols = cat_cols.drop("final_grade")
#num_cols = num_cols.drop("final_exam_score","student_id")

In [ ]:
cat_cols = df.select_dtypes(include=["object"]).columns
num_cols = df.select_dtypes(include=["int64","float64"]).columns
print("Categorical columns :")
print(cat_cols)
print("\nNumerical columns :")
print(num_cols)

Categorical columns :
Index(['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope'], dtype='object')

Numerical columns :
Index(['Age', 'RestingBP', 'Cholesterol', 'FastingBS', 'MaxHR', 'Oldpeak',
       'HeartDisease'],
      dtype='object')

In [ ]:
encoded = pd.get_dummies(df[cat_cols])
encoded = encoded.astype(int)
encoded

,Sex_F,Sex_M,ChestPainType_ASY,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ExerciseAngina_N,ExerciseAngina_Y,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,0,1,0,1,0,0,0,1,0,1,0,0,0,1
1,1,0,0,0,1,0,0,1,0,1,0,0,1,0
2,0,1,0,1,0,0,0,0,1,1,0,0,0,1
3,1,0,1,0,0,0,0,1,0,0,1,0,1,0
4,0,1,0,0,1,0,0,1,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,0,1,0,0,0,1,0,1,0,1,0,0,1,0
914,0,1,1,0,0,0,0,1,0,1,0,0,1,0
915,0,1,1,0,0,0,0,1,0,0,1,0,1,0
916,1,0,0,1,0,0,1,0,0,1,0,0,1,0
917,0,1,0,0,1,0,0,1,0,1,0,0,0,1

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scalered = scaler.fit_transform(df[num_cols])
scalered = pd.DataFrame(scalered, columns = num_cols)
scalered

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
0,-1.433140,0.410909,0.825070,-0.551341,1.382928,-0.832432,-1.113115
1,-0.478484,1.491752,-0.171961,-0.551341,0.754157,0.105664,0.898380
2,-1.751359,-0.129513,0.770188,-0.551341,-1.525138,-0.832432,-1.113115
3,-0.584556,0.302825,0.139040,-0.551341,-1.132156,0.574711,0.898380
4,0.051881,0.951331,-0.034755,-0.551341,-0.581981,-0.832432,-1.113115
...,...,...,...,...,...,...,...
913,-0.902775,-1.210356,0.596393,-0.551341,-0.188999,0.293283,0.898380
914,1.536902,0.627078,-0.053049,1.813758,0.164684,2.357094,0.898380
915,0.370100,-0.129513,-0.620168,-0.551341,-0.857069,0.293283,0.898380
916,0.370100,-0.129513,0.340275,-0.551341,1.461525,-0.832432,0.898380
917,-1.645286,0.302825,-0.217696,-0.551341,1.422226,-0.832432,-1.113115

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test =train_test_split(encoded, y, test_size=0.20, random_state=42)

In [ ]:
#from sklearn.linear_model import LogisticRegression
#from sklearn.neighbors import KNeighborsClassifier
#from sklearn.naive_bayes import GaussianNB
#from sklearn.linear_model import LinearRegression

#model = LogisticRegression()
#model.fit(X_train, y_train)

#model = KNeighborsClassifier(n_neighbors=3)
#model.fit(X_train, y_train)

#model = GaussianNB()
#model.fit(X_train, y_train)

#model = LinearRegression()
#model.fit(X_train, y_train)

In [ ]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()
model.fit(X_train, y_train)

GaussianNB()

In [ ]:
#pred_LOR = model.predict(X_test)
#pred_KNN = model.predict(X_test)
#pred_NB = model.predict(X_test)
#pred_LR = model.predict(X_test)

In [ ]:
pred_NB = model.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score

acc = accuracy_score(pred_KNN, y_test)
print("\nAccuracy Score of KNN :")
print(acc)

Accuracy Score of KNN :
0.8097826086956522

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

cf = confusion_matrix(pred_NB, y_test)
print("Confusion Matrix :")
print(cf)

print("\nClassification Report :")
cr = classification_report(pred_NB, y_test)
print(cr)

Confusion Matrix :
[[68 26]
 [ 9 81]]

Classification Report :
              precision    recall  f1-score   support

           0       0.88      0.72      0.80        94
           1       0.76      0.90      0.82        90

    accuracy                           0.81       184
   macro avg       0.82      0.81      0.81       184
weighted avg       0.82      0.81      0.81       184

In [ ]:
print("Predicted Values:")
print(pred_LR[:10])

print("\nActual Values:")
print(y_test[:10])

from sklearn.metrics import r2_score

r2 = r2_score(pred_LR, y_test)
print("\nR2 Score :")
print(r2)

Predicted Values:

NameError: name 'pred_LR' is not defined

In [ ]:
from sklearn.metrics import f1_score, accuracy_score, confusion_matrix, precision_score, recall_score

cm = confusion_matrix(pred_LOR, y_test)
print("Confusion Matrix :")
print(cm)

acc = accuracy_score(pred_LOR, y_test)
print("\nAccuracy Score of LOR:")
print(acc)

prec = precision_score(pred_LOR, y_test)
print("\nPrecision Score :")
print(prec)

rec = recall_score(pred_LOR, y_test)
print("\nRecall Score :")
print(rec)

f1 = f1_score(pred_LOR, y_test)
print("\nF1 Score :")
print(f1)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test =train_test_split(encoded, y, test_size=0.20, random_state=42)

model_LOR = LogisticRegression()
model_LOR.fit(X_train, y_train)

model_KNN = KNeighborsClassifier(n_neighbors=5)
model_KNN.fit(X_train, y_train)

model_NB = GaussianNB()
model_NB.fit(X_train, y_train)

pred_LOR = model_LOR.predict(X_test)
pred_KNN = model_KNN.predict(X_test)
pred_NB = model_NB.predict(X_test)


# Create comparison table
results = pd.DataFrame({
    "Algorithm": [
        "Logistic Regression",
        "KNN (k=5)",
        "Naive Bayes"
    ],
    "Accuracy": [
        accuracy_score(y_test, pred_LOR),
        accuracy_score(y_test, pred_KNN),
        accuracy_score(y_test, pred_NB)
    ],
    "Precision": [
        precision_score(y_test, pred_LOR),
        precision_score(y_test, pred_KNN),
        precision_score(y_test, pred_NB)
    ],
    "Recall": [
        recall_score(y_test, pred_LOR),
        recall_score(y_test, pred_KNN),
        recall_score(y_test, pred_NB)
    ],
    "F1 Score": [
        f1_score(y_test, pred_LOR),
        f1_score(y_test, pred_KNN),
        f1_score(y_test, pred_NB)
    ]
})
print("Comparison Table:")
print("\n",results)

best_model = results.loc[results["Accuracy"].idxmax()]

print("\nBest Model:")
print(best_model)

Comparison Table:

              Algorithm  Accuracy  Precision    Recall  F1 Score
0  Logistic Regression  0.826087   0.894737  0.794393  0.841584
1            KNN (k=5)  0.831522   0.865385  0.841121  0.853081
2          Naive Bayes  0.809783   0.900000  0.757009  0.822335

Best Model:
Algorithm    KNN (k=5)
Accuracy      0.831522
Precision     0.865385
Recall        0.841121
F1 Score      0.853081
Name: 1, dtype: object

In [ ]:
#Conclusion

#Best Model: KNN (k=5)

#Reason:
#KNN (k=5) is the best model because it has the highest Accuracy (83.15%) and the highest F1 Score (85.31%) among the three algorithms.
#It also has the highest Recall (84.11%), which means it correctly identifies more instances than the other models.
#Therefore, KNN provides the best overall performance for this dataset.